config/routes.rb
EmbededApp::Application.routes.draw do

  mount ResqueWeb::Engine => "/resque_web"

  controller :sessions do
    get 'login' => :new
    get 'auth/shopify/callback' => :show
  end


  resource :recomify, controller: :recomify, only: [] do
    get 'settings'
    put 'update'
  end

  resources :recommendations, only: [:create, :index, :show]
  resources :customers, only: [:index, :show]

  post 'post_test' => 'static#post_test'
  #get 'modal' => "home#modal", :as => :modal
  #get 'modal_buttons' => "home#modal_buttons", :as => :modal_buttons
  #get 'regular_app_page' => "home#regular_app_page"
  #get 'help' => "home#help"
  #get 'pagination' => "home#pagination"
  #get 'breadcrumbs' => "home#breadcrumbs"
  #get 'buttons' => "home#buttons"
  #get 'form_page' => "home#form_page"
  #post 'form_page' => "home#form_page"
  #get 'error' => 'home#error'
  #get 'index' => 'home#index'

  #root :to => 'recomify#settings'
  root :to => 'recommendations#index'
  #root :to => 'static#hello'
  #root :to => 'home#index'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :shop
  has_many :recommendations, dependent: :destroy
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :recommendations
  belongs_to :shop
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :customer
  belongs_to :product
  belongs_to :shop

  after_create :send_email

  def send_email
    puts ">>>> sending email <<<"
    Resque.enqueue(RecommendationEmailJob, :customers_email_queue, id)
  end
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  store_accessor :settings

  has_many :customers, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :recommendations, dependent: :destroy
  
  after_initialize :set_settings 
  after_create :set_additional_data

  def self.store(session)
     shop = Shop.new(domain: session.url, token: session.token)
     shop.save!
     shop.id
   end

   def self.retrieve(id)
     if shop = Shop.where(id: id).first
       ShopifyAPI::Session.new(shop.domain, shop.token)
     end
   end

  def set_settings
    return if self.settings
    self.settings = {width: 200, border_size: 4, border_color: '#3a4ed1', font_family: 'Helvetica Neue',
      text_color: '#000000', bg_color: '#a7ccaa', button_color: '#38d9c6'}
  end

  def set_additional_data
    Resque.enqueue(ShopAdditionalAttributesSetter, id)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :set_current_shop
  before_action :add_headers
  #before_action :test

  def add_headers
    response.headers['Access-Control-Allow-Origin'] = request.headers['Origin'] || '*'
    response.headers['Access-Control-Allow-Credentials'] = 'true'
  end

  def set_current_shop
    return unless session[:shopify]
    @current_shop ||= Shop.where(id: session[:shopify]).first
    reset_session unless @current_shop
  end

  def current_shop_id
    session[:shopify]
  end

  def test
    session.clear
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  around_filter :shopify_session

  def index
    @customers = Customer.includes(:recommendations).all
  end

  def show
    @customer = Customer.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  around_filter :shopify_session
  
  def index
  end

  def modal
  end

  def modal_buttons
  end

  def regular_app_page
  end

  def buttons
  end

  def help
  end

  def error
    raise "An error page"
  end

  def form_page
    if request.post?
      if params[:name].present?
        flash[:notice] = "Created #{ params[:colour] } unicorn: #{ params[:name] }."
      else
        flash[:error] = "Name must be set."
      end
    end
  end

  def pagination
    @total_pages = 3
    @page = (params[:page].presence || 1).to_i
    @previous_page = "/pagination?page=#{ @page - 1 }" if @page > 1
    @next_page = "/pagination?page=#{ @page + 1 }" if @page < @total_pages
  end

end

app/controllers/recomify_controller.rb
class RecomifyController < ApplicationController
  around_filter :shopify_session

  def settings
  end

  def update
    @current_shop.update_attributes settings: params[:shop][:settings]
    flash[:notice] = "Updated form style"
    Resque.enqueue(RecommendationSnippetUpdater, @current_shop.id, params[:shop][:settings].merge(server_address: ENV['server_address']))
  	redirect_to settings_recomify_path
  end

end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController

  around_filter :shopify_session, except: [:create]
  before_filter :add_headers, only: [:create]

  def show
    @recommendation = Recommendation.find(params[:id])
  end

  def index
    @recommendations = Recommendation.includes(:customer, :product).all
  end

  def create
    email_regex = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/

    return render plain: "Email format is incorrect" unless email_regex.match(recommendation_params[:email])
    return render plain: "Comment cannot be empty" if recommendation_params[:comment] == ""
    
    render plain: "Recommendation submitted!"
    Resque.enqueue(RecommendationPersistor, product_price, recommendation_params, params[:product][:product_id], params[:customer][:customer_id], shop_domain)
  end

  private

  def recommendation_params
    params.require(:recommendation).permit(:email,:comment) 
  end

  def product_id
    params[:product][:product_id]
  end

  def shop_domain
    params[:shop][:domain]
  end

  def customer_id
    params[:customer][:customer_id]
  end

  def product_price
    params[:product][:price]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout :false

  def new
    authenticate if params[:shop]
  end

  def show
    if response = request.env['omniauth.auth']
      sess = ShopifyAPI::Session.new(params[:shop],response['credentials']['token'])

#      Shop.first.update_attributes(token: response['credentials']['token'], domain: "http://#{params[:shop]}")

      session[:shopify] = ShopifySessionRepository.store(sess)

      flash[:notice] = "Logged in"
      redirect_to return_address
    else
      flash[:error] = "Could not log in to Shopify store."
      redirect_to :action => 'new'
    end
  end

  protected

  def authenticate
    #
    # Instead of doing a backend redirect we need to do a javascript redirect
    # here. Open the app/views/commom/iframe_redirect.html.erb file to understand why.
    #
    if shop_name = sanitize_shop_param(params)
      @redirect_url = "/auth/shopify?shop=#{shop_name}"
      render "/common/iframe_redirect", :format => [:html], layout: false
    else
      redirect_to return_address
    end
  end

  def return_address
    session[:return_to] || root_url
  end

  def sanitize_shop_param(params)
    return unless params[:shop].present?
    return unless domain = ShopifyApp.configuration.myshopify_domain.presence || "myshopify.com"

    name = params[:shop].to_s.strip
    name += ".#{domain}" if !name.include?(domain) && !name.include?(".")
    name.sub!(%r|https?://|, '')

    u = URI("http://#{name}")
    u.host.ends_with?(".#{domain}") ? u.host : nil
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def hello
  end

  def post_test
    puts params
    puts ShopifyAPI::Product.all

    return render plain: "It's submitted!!!!!"
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/recomify_helper.rb
module RecomifyHelper
  def product_admin_url product
    "/products/" + product.product_id
  end

  def product_price product
    product.shop.money_format.gsub("{{amount}}",product.price)
  end

  def product_url product
    "http://" + product.shop.domain + product.url
  end

  def get_price  product
    product.shop.money_format.gsub("{{amount}}",product.price) 
  end

end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
  
  def active_nav_class(name, action = nil)
    if action.present?
      return if controller.action_name != action
    end
    
    'active' if controller.controller_name =~ /#{name}/i
  end
  
end

app/views/common/_flash.html.erb
<% if flash[:notice] %>
  ShopifyApp.flashNotice("<%= flash[:notice] %>");
<% end %>

<% if flash[:error] %>
  ShopifyApp.flashError("<%= flash[:error] %>");
<% end %>

app/views/common/_setting_bar.html.erb
<ul class="section-tabs">
  <li class=<%= params[:controller] == 'recommendations' and params[:action] == 'index' ? 'active' : ''%>> <a href="<%= recommendations_path %>"> Recommendations </a> </li>
  <li class=<%= params[:controller] == 'customers' and params[:action] == 'index' ? 'active' : ''%>> <a href="<%=customers_path%>"> Customers </a> </li>
  <li class=<%= params[:action] == 'settings' ? 'active' : '' %>> <a href="<%= settings_recomify_path %>"> Settings </a> </li>
 </ul>

app/views/common/_top_bar.html.erb
<script type="text/javascript">
  window.mainPageTitle = 'Main Page';

  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: window.mainPageTitle,
      icon: '/icon.png',
      buttons: {
        secondary: {
          label: "Documentation",
          href: "http://docs.shopify.com/embedded-app-sdk",
          target: 'new'
        }
      }
    });
  });
</script>

app/views/common/iframe_redirect.html.erb
<!--
  As we are inside an iframe, redirecting the iframe to the OAuth page will
  brake it. So we need to ask the parent to do the redirect.

  This redirect can't be done on server side, or the browser will block the
  OAuth page to be rendered. You need to do a full page redirect.
-->
<script type="text/javascript">
  window.top.location.href = "<%= @redirect_url %>";
</script>

app/views/customers/index.html.erb
<script type="text/javascript">
  window.mainPageTitle = 'Customers';
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: window.mainPageTitle
    });
  });
</script>

<div class="section">
  <div class="section-content">
    <div class="section-row">
      <div class="section-listing">
        <div class="section-options">
          <%= render partial: 'common/setting_bar' %>
          <div class="section-content">
            <table class="table-section">
              <thead>
                <tr>
                  <th><b>Name</b></th>
                  <th><b>Email</b></th>
                  <th><b>Num of Recommendations</b></th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
              <% @customers.each do |customer| %>
                <tr>
                <td><%= customer.name %></td>
                <td><%= customer.email %></td>
                <td><%= customer.recommendations.size %></td>
                <td><a href="<%= customer_path customer %>" class="btn default">Show Recommendations</a></td>
                <td><a href="#" onclick="ShopifyApp.redirect('/customers/<%= customer.customer_id %>');" class="btn primary">Customer Profile</a></td>
                </tr>
              <% end %>
                </tbody>
              </table>    
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

        

app/views/customers/show.html.erb
<script type="text/javascript">
window.mainPageTitle = "Recommendations by <%= @customer.name %> ";

ShopifyApp.ready(function(){
  ShopifyApp.Bar.initialize({
    title: window.mainPageTitle,
    buttons: {
      secondary: [
        {
          label: "Back",
          href: "<%=customers_path%>",
          target: 'app'
        }
      ]
    }
  });
});
</script>


<div class="section">
  <div class="section-content">
    <div class="section-row">
      <div class="section-cell">
        <table class="table-section">
          <%= render partial: 'recommendations/recommendation_partial', locals: {recommendations: @customer.recommendations} %>
      </div>
    </div>
  </div>
</div>            

app/views/home/breadcrumbs.html.erb
<script type="text/javascript">
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: 'Breadcrumbs',
      breadcrumb: {
        label: "Regular Page",
        href: "/regular_app_page",
        target: 'app'
      },
      icon: '/icon.png',
      buttons: {
        secondary: {
          label: "Back",
          href: "/",
          target: 'app'
        }
      }
    });
  });
</script>

<h1>Breadcrumbs</h1>

<p>In addition to the page title, a single middle level of breadcrumbs can be inserted between the root of the app and the current page. It is defined the same way as a button with label, href, target, loading, etc..</p>

<p>If there is no title set the breadcrumb will not appear.</p>

app/views/home/buttons.html.erb
<script type="text/javascript">
  window.mainPageTitle = 'Buttons Page';

  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: window.mainPageTitle,
      buttons: {
        primary: {label: "Primary", loading: false, callback: function(){ alert('Primary clicked'); } },
        secondary: [
          {label: "Normal", loading: false, callback: function(){ alert('Normal clicked'); } },
          {label: "Danger", loading: false, style: 'danger', callback: function(){ alert('Danger clicked'); } },
          {label: "Disabled", loading: false, style: 'disabled', callback: function(){ alert('Disabled clicked'); } }
        ]
      }
    });
  });
</script>

<p>
  Buttons can be styled as "danger", "disabled", "primary", or null/undefined as default.
</p>

app/views/home/form_page.html.erb
<script type="text/javascript">
   window.mainPageTitle = 'Form page';
   ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: window.mainPageTitle,
      icon: '/icon.png',
      buttons: {
        primary: {
          label: "Create Unicorn",
          message: 'save-unicorn-form-message'
        },
        secondary: {
          label: "Back",
          href: "/",
          target: 'app'
        }
      }
    });

  <% if flash[:notice] %>
    ShopifyApp.flashNotice("<%= flash[:notice] %>");
  <% end %>

  <% if flash[:error] %>
    ShopifyApp.flashError("<%= flash[:error] %>");
  <% end %>

  });
</script>

<h1>Create new Unicorn</h1>

<p>A normal form submitted by a data tag and a button in Shopify. Embedded apps can mostly work exactly like a normal app, except with Shopify admin UI integration.</p>

<form method="POST" action="form_page" data-shopify-app-submit="save-unicorn-form-message">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <p>
    <label>Name:</label>
    <input type="text" name="name"/>
  </p>

  <p>
    <label>Colour:</label>
    <select name="colour">
      <option>Pink</option>
      <option>Rainbow</option>
      <option>Purple</option>
    </select>
  </p>

</form>

app/views/home/help.html.erb
<script type="text/javascript">
   window.mainPageTitle = 'Help Page';

  ShopifyApp.ready(function(){
    ShopifyApp.Bar.setTitle(window.mainPageTitle);
    ShopifyApp.Bar.loadingOff();
  });
</script>

<h2>Hey! This is the help page.</h2>

<p>You can go back to the previous page clicking on the breadcrumb link on the top bar. =)</p>

app/views/home/index.html.erb
<%= render "/common/top_bar" %>

<h2>Shopify Embedded Example.</h2>

<p>This application demos the various ways an app can now interact with the Shopify Admin. See the project README for details.</p>

<p><a href="regular_app_page">Links to another page</a> work normally.</p>

<h2>Function calls</h2>
<ul>
  <li><a href="#" onclick="ShopifyApp.Bar.loadingOff()">Turn spinner off</a></li>
  <li><a href="#" onclick="ShopifyApp.Bar.loadingOn()">Turn spinner on</a></li>
  <li><a href="#" onclick="window.mainPageTitle = window.mainPageTitle + '!'; ShopifyApp.Bar.setTitle(window.mainPageTitle)">Add an exclamation mark to the title</a></li>
  <li><a href="#" onclick="ShopifyApp.redirect('/orders')">Redirect to /orders within the Shopify Admin</a></li>

  <li><a href="#" onclick="ShopifyApp.flashNotice('Flash a notice message.');">Flash notice</a></li>
  <li><a href="#" onclick="ShopifyApp.flashError('Flash an error message.');">Flash error</a></li>
  <li><a href="#" onclick="ShopifyApp.Bar.setPagination({previous: {loading: false, callback: function(){alert('Previous clicked'); } }}); return false">Add pagination buttons</a></li>
</ul>


<!-- 
  This is example code, focusing on simplicity.
  Try not to use 'onclick' attributes in real applications. Use unobtrusive JavaScript instead.
  http://en.wikipedia.org/wiki/Unobtrusive_JavaScript)

  See modals.js for the implementation of these calls.
-->

<h2>Modal Windows</h2>
<ul>
  <li><a href="#" onclick="alertModal()">Alert modal</a></li>
  <li><a href="#" onclick="confirmModal()">Confirm modal</a></li>
  <li><a href="#" onclick="inputModal('Enter a value:')">Prompt modal</a></li>
  <li><a href="#" onclick="newModal('<%= modal_url %>','This is a custom modal title')">Modal window containing an iframe</a></li>
  <li><a href="#" onclick="newButtonModal('<%= modal_buttons_url %>','This modal has many buttons')">Modal window with a variety of buttons</a></li>
</ul>

<h2>Integrations</h2>
<ul>
  <li><a href="form_page">Go to form page</a></li>
  <li><a href="pagination">Pagination links</a></li>
  <li><a href="breadcrumbs">Breadcrumbs</a></li>
  <li><a href="buttons">Buttons</a></li>
</ul>

<h2>Error pages</h2>
<ul>
  <li><a href="/does_not_exist">Error 404</a></li>
  <li><a href="/error">Error 500</a></li>
</ul>

app/views/home/modal.html.erb
<h2>This content is displayed on a modal window!</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tollenda est atque extrahenda radicitus. Animum autem reliquis rebus ita perfecit, ut corpus; Duo Reges: constructio interrete. Dat enim intervalla et relaxat. Igitur neque stultorum quisquam beatus neque sapientium non beatus. Est autem etiam actio quaedam corporis, quae motus et status naturae congruentis tenet; 
Quam illa ardentis amores excitaret sui! Cur tandem? Nos commodius agimus. Nihil minus, contraque illa hereditate dives ob eamque rem laetus. Quis enim est, qui non videat haec esse in natura rerum tria? Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Summus dolor plures dies manere non potest? Cum autem in quo sapienter dicimus, id a primo rectissime dicitur. Levatio igitur vitiorum magna fit in iis, qui habent ad virtutem progressionis aliquantum. At ego quem huic anteponam non audeo dicere; Sed venio ad inconstantiae crimen, ne saepius dicas me aberrare; 
Quid enim de amicitia statueris utilitatis causa expetenda vides. Quodcumque in mentem incideret, et quodcumque tamquam occurreret. Age nunc isti doceant, vel tu potius quis enim ista melius? Cum id fugiunt, re eadem defendunt, quae Peripatetici, verba. Beatus autem esse in maximarum rerum timore nemo potest. Non dolere, inquam, istud quam vim habeat postea videro; Omnia contraria, quos etiam insanos esse vultis. Duo enim genera quae erant, fecit tria. Ergo, si semel tristior effectus est, hilara vita amissa est? 
Videmusne ut pueri ne verberibus quidem a contemplandis rebus perquirendisque deterreantur? Paria sunt igitur. At ego quem huic anteponam non audeo dicere; Ex eorum enim scriptis et institutis cum omnis doctrina liberalis, omnis historia. Mene ergo et Triarium dignos existimas, apud quos turpiter loquare? Ut non sine causa ex iis memoriae ducta sit disciplina. Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Hoc est non modo cor non habere, sed ne palatum quidem. </p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tu quidem reddes; Quis istud possit, inquit, negare? 
Cave putes quicquam esse verius. Cave putes quicquam esse verius. Isto modo ne improbos quidem, si essent boni viri. Non quam nostram quidem, inquit Pomponius iocans; 
Propter nos enim illam, non propter eam nosmet ipsos diligimus. Non igitur de improbo, sed de callido improbo quaerimus, qualis Q. Ut optime, secundum naturam affectum esse possit. Duo Reges: constructio interrete. Quae quidem vel cum periculo est quaerenda vobis; 
Prodest, inquit, mihi eo esse animo. Eaedem res maneant alio modo. Bonum patria: miserum exilium. In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret. </p>  

app/views/home/modal_buttons.html.erb
<h2>This content is content is an iframe.</h2>

<p>
  Modals accept an object of buttons. The object can contain keys as follows:

  <ul>
    <li>`primary`: Max 2 button. Floated right. Defaults to green, and the only button that can be green.</li>
    <li>`secondary`: Max 2 buttons. Floated right after the primary button.</li>
    <li>`tertiary`: Max 2 buttons. Floated left.</li>
  </ul>
</p>

app/views/recomify/index_settings.html.erb
<script type="text/javascript">
   window.mainPageTitle = 'Form Settings';
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: window.mainPageTitle,
      icon: '/icon.png',
      buttons: {
        primary: {
          label: "Create Unicorn",
          message: 'save-unicorn-form-message'
        },
        secondary: {
          label: "Back",
          href: "/",
          target: 'app'
        }
      }
    });

  <% if flash[:notice] %>
    ShopifyApp.flashNotice("<%= flash[:notice] %>");
  <% end %>

  <% if flash[:error] %>
    ShopifyApp.flashError("<%= flash[:error] %>");
  <% end %>

  });
</script>

<!-- This is a section -->
<div class="section">
  <div class="section-content">
    <div class="section-row">
      <div class="section-listing">
        <div class="section-options">
          <%= render partial: 'setting_bar' %>
          <div class="section-content">

            <div class="section-content inline-block">
              <div class="section-row">
                <div class="section-cell">

                  <%= simple_form_for Shop.instance, url: update_settings_recomify_path, method: :put do |f| %>
                    <%= f.simple_fields_for :settings do |d| %>
                      <% f.object.settings.keys.each_slice(2) do |arr| %>

                        <div class="cell-container">
                          <% arr.each do |key| %>
                            <div class="cell-column">
                              <% if key.include? "color" %>
                                <%= d.input key, :input_html => {:value => f.object.settings[key], :style => 'width: 200px'}, :required => false, as: :minicolors%>
                              <% else %>
                                <%= d.input key, :input_html => {:value => f.object.settings[key], :style => 'width: 226px'}, :required => false%>
                              <% end %>
                            </div>
                          <% end %>
                        </div>

                      <% end %>
                    <% end %>
                    <center> <%= f.submit 'Update form style', :class => 'btn primary' %> </center>
                  <% end %>

                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/recomify/settings.html.erb
<script type="text/javascript">
   window.mainPageTitle = 'Form Settings';
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: window.mainPageTitle
    });

});
</script>

<!-- This is a section -->
<div class="section">
  <div class="section-content">
    <div class="section-row">
      <div class="section-listing">
        <div class="section-options">
          <%= render partial: 'common/setting_bar' %>
          <div class="section-content">

            <div class="section-content inline-block">
              <div class="section-row">
                <div class="section-cell">

                  <%= simple_form_for @current_shop, url: recomify_path, method: :put do |f| %>
                    <%= f.simple_fields_for :settings do |d| %>
                      <% f.object.settings.keys.each_slice(2) do |arr| %>

                        <div class="cell-container">
                          <% arr.each do |key| %>
                            <div class="cell-column">
                              <% if key.include? "color" %>
                                <%= d.input key, :input_html => {:value => f.object.settings[key], :style => 'width: 200px'}, :required => false, as: :minicolors%>
                              <% else %>
                                <%= d.input key, :input_html => {:value => f.object.settings[key], :style => 'width: 226px'}, :required => false%>
                              <% end %>
                            </div>
                          <% end %>
                        </div>

                      <% end %>
                    <% end %>
                    <center> <%= f.submit 'Update form style', :class => 'btn primary' %> </center>
                  <% end %>

                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/recommendations/_recommendation_partial.html.erb
<table class="table-section">
              <thead>
                <tr>
                  <th><b>From Customer</b></th>
                  <th><b>Sent to</b></th>
                  <th><b>Product name</b></th>
                  <th><b>At</b></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
<% recommendations.each do |recommendation| %>
  <tr>
    <td><%= recommendation.customer.name %></td>
    <td><%= recommendation.email %></td>
    <td><a href="#" onclick="ShopifyApp.redirect('<%= product_admin_url recommendation.product %>')"><%=recommendation.product.name%></a> </td>
    <td><%= recommendation.created_at %> </td>
    <td><a href="#" class="btn default" onclick="newModal('<%= recommendation_path(recommendation) %>','Comment')">Show Comment</a></td>
  </tr>
<% end %>

              </tbody>
              </table>    

app/views/recommendations/settings.html.erb
<script type="text/javascript">
   window.mainPageTitle = 'Form Settings';
  ShopifyApp.ready(function(){
    ShopifyApp.Bar.initialize({
      title: window.mainPageTitle,
      icon: '/icon.png',
      buttons: {
        primary: {
          label: "Create Unicorn",
          message: 'save-unicorn-form-message'
        },
        secondary: {
          label: "Back",
          href: "/",
          target: 'app'
        }
      }
    });

  <% if flash[:notice] %>
    ShopifyApp.flashNotice("<%= flash[:notice] %>");
  <% end %>

  <% if flash[:error] %>
    ShopifyApp.flashError("<%= flash[:error] %>");
  <% end %>

  });
</script>

<!-- This is a section -->
<div class="section">
  <div class="section-content">
    <div class="section-row">
      <div class="section-listing">
        <div class="section-options">
          <%= render partial: 'setting_bar' %>
          <div class="section-content">

            <div class="section-content inline-block">
              <div class="section-row">
                <div class="section-cell">

                  <%= simple_form_for Shop.instance, url: update_settings_recommendations_path, method: :put do |f| %>
                    <%= f.simple_fields_for :settings do |d| %>
                      <% f.object.settings.keys.each_slice(2) do |arr| %>

                        <div class="cell-container">
                          <% arr.each do |key| %>
                            <div class="cell-column">
                              <% if key.include? "color" %>
                                <%= d.input key, :input_html => {:value => f.object.settings[key], :style => 'width: 15em'}, :required => false, as: :minicolors%>
                              <% else %>
                                <%= d.input key, :input_html => {:value => f.object.settings[key], :style => 'width: 15em'}, :required => false%>
                              <% end %>
                            </div>
                          <% end %>
                        </div>

                      <% end %>
                    <% end %>
                    <center> <%= f.submit 'Update form style', :class => 'btn primary' %> </center>
                  <% end %>

                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/recommendations/show.html.erb
<p>
<%= @recommendation.comment %>
</p>